### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by AliMora83** [chingu-voyages/v45-tier3-team-34#34]
As a **user**,
I want to **be greeted with a visually appealing and informative hero section**,
So that **I can understand the purpose of the website and what it has to offer**.

**Acceptance Criteria:**
- should include a clear and concise message about the website.
- should include **two** call to action that encourages users to learn more about the website and **Join**.
- (Nice-to-have) should use **high-quality images and videos** to capture the user's attention.

Example:
![Screenshot 2023-08-11 at 10 45 19](https://github.com/chingu-voyages/v45-tier3-team-34/assets/56822813/ff1f1020-9488-406a-8e79-23cbd3bb5f59)

**Comment by AliMora83** [comment]
Hey @varchodi 🥳 
Hope you are well.

How is this going? 🤔

**Comment by varchodi** [comment]
i didnt have som much time for this page , i was workin on login and register page , but it will be finished during the weekend;

**Comment by AliMora83** [comment]
Closed PR: #54 
Thank you @varchodi 🥳
